# This is an R function that ranks all Mouse genes in the Bioconductor library TxDb.Mmusculus.UCSC.mm10.refGene using 
# Jensen-Shannon distance (JSD) and the average mutual information based on the method described in https://doi.org/10.1186/s12859-019-2777-6. 
# It should be run within an R session.

# The following R libraries must be installed:
#   - GenomicFeatures
#   - GenomicRanges
#   - rtracklayer
#   - TxDb.Mmusculus.UCSC.mm10.refGene

# The script uses BIGWIG (BW) files with JSD values across the genome from the comparison of 2 samples. BW files are converted from the BED files generated by the informME
# pipeline using the BedToBigWIG tool from the UCSC Genome Browser (https://anaconda.org/bioconda/ucsc-bedgraphtobigwig).

# The statistical test creates a null distribution based on comparisons among control samples.



# Below are the scripts for the 3 tests included in the paper, indicating the BW files with JSD from the relevant comparisons (generated by the informME pipeline).
# All tests use the same script that includes the functions to perform the ranking of genes and statistical testing (

# 1) Old vs Young comparison of whole dorsal skin samples:




# 2) Old vs Old treated (OSKM) comparison of whole dorsal skin samples





# 3) Old vs Young comparison of isolated epidermis from tail skin samples




Add some comment in previous informME.


