# This is an R function that ranks all Mouse genes in the Bioconductor library TxDb.Mmusculus.UCSC.mm10.knownGene using 
# Jensen-Shannon distance (JSD) and the average mutual information based on the method described in https://doi.org/10.1186/s12859-019-2777-6. 
# It should be run within an R session.

# The following R libraries must be installed:
#   - GenomicFeatures
#   - GenomicRanges
#   - rtracklayer
#   - TxDb.Mmusculus.UCSC.mm10.refGene

# The script uses BIGWIG (BW) files with JSD values across the genome from the comparison of 2 samples. BW files are converted from the BED files generated by the informME
# pipeline using the BedToBigWIG tool from the UCSC Genome Browser (https://anaconda.org/bioconda/ucsc-bedgraphtobigwig).

# The statistical test creates a null distribution based on comparisons among control samples.



# Below are the scripts for the 3 tests included in the paper, indicating the BW files with JSD from the relevant comparisons (generated by the informME pipeline).
# Equivalence between sample IDs and sample names as referenced in the paper is included in the Expanded View of the paper.
# All tests use the same script with the source code including the functions to perform the ranking of genes and statistical testing (JSD_ranking_source_code.sh).

####################################################################
# 1) Old vs Young comparison of whole dorsal skin samples:
# Source code
source('JSD_ranking_source_code.R')

# Directories
inFolder <- 'skin_bw_files/'
outFolder <- 'results/'

# Comparisons among control samples (to make null distribution)
refVrefFiles <-  c("JSD-Y4F-1-VS-Y4F-3.bw",
                   "JSD-Y4F-1-VS-Y4F-4.bw",
		   "JSD-Y4F-3-VS-Y4F-4.bw")

# Comparisons between treated and control samples
testVrefFiles <- c("JSD-5760-con-VS-Y4F-4.bw",
		   "JSD-5761-con-VS-Y4F-4.bw",
		   "JSD-5762-con-VS-Y4F-4.bw",
		   "JSD-5764-con-VS-Y4F-4.bw")
            
#Name of the groups
tName="old"
rName="young"

# Function
rankGenes(refVrefFiles,testVrefFiles,inFolder,outFolder,tName,rName)
####################################################################

####################################################################
# 2) Old vs Old treated (OSKM) comparison of whole dorsal skin samples:

# Source code
source('JSD_ranking_source_code.R')
# Directories
inFolder <- 'skin_bw_files/'
outFolder <- 'results/'

# Comparisons among control samples (to make null distribution)
refVrefFiles <-  c("JSD-5760-con-VS-5761-con.bw",
                   "JSD-5760-con-VS-5762-con.bw",
		   "JSD-5760-con-VS-5764-con.bw",
                   "JSD-5761-con-VS-5762-con.bw",
                   "JSD-5761-con-VS-5764-con.bw",
                   "JSD-5762-con-VS-5764-con.bw")

# Comparisons between treated and control samples
testVrefFiles <- c("JSD-253-dox-VS-5761-con.bw",
                   "JSD-284-dox-VS-5761-con.bw",
                   "JSD-285-dox-VS-5761-con.bw",
                   "JSD-288-dox-VS-5761-con.bw",
                   "JSD-904-dox-VS-5761-con.bw")
            
# Name of the groups
tName="old_treated"
rName="old"

# Function
rankGenes(refVrefFiles,testVrefFiles,inFolder,outFolder,tName,rName)
####################################################################

####################################################################
# 3) Old vs Young comparison of isolated epidermis from tail skin samples:

# Source code
source('JSD_ranking_source_code.R')
# Directories
inFolder <- 'skin_bw_files/'
outFolder <- 'results/'

# Comparisons among control samples (to make null distribution)
refVrefFiles <-  c("JSD-Y-458-VS-Y-459.bw",
		   "JSD-Y-458-VS-Y-461.bw",
		   "JSD-Y-458-VS-Y-463.bw",
		   "JSD-Y-458-VS-Y-464.bw",
		   "JSD-Y-459-VS-Y-461.bw",
		   "JSD-Y-459-VS-Y-463.bw",
		   "JSD-Y-459-VS-Y-464.bw",
		   "JSD-Y-461-VS-Y-463.bw",
		   "JSD-Y-461-VS-Y-464.bw",
		   "JSD-Y-463-VS-Y-464.bw")

# Comparisons between treated and control samples
testVrefFiles <- c("JSD-O-005-VS-Y-458.bw",
		   "JSD-O-989-VS-Y-458.bw",
                   "JSD-O-990-VS-Y-458.bw",
                   "JSD-O-991-VS-Y-458.bw",
                   "JSD-O-992-VS-Y-458.bw")

            
# Name of the groups
tName="old"
rName="young"

# Function
rankGenes(refVrefFiles,testVrefFiles,inFolder,outFolder,tName,rName)
####################################################################


